#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  25
yabai -m config bottom_padding               25
yabai -m config left_padding                 25
yabai -m config right_padding                25
yabai -m config window_gap                   25

# float system preferences
yabai -m rule --add app="^System Preferences$" manage=off

# Float Spotify in the middle of the screen
# yabai -m rule --add label="Float Spotify centered" app="^Spotify\$" manage=off grid=6:4:1:1:2:4
# yabai -m signal --add label="Move Activated App to current Space" event=application_activated action="node $HOME/.config/yabai/moveActivatedWindow.js"
yabai -m rule --add app="^Digital Colou?r Meter$" manage=off

if [ `hostname` = "zachary-jones-od-mac" ] then
  yabai -m rule --add label="Messages App" app="^Messages$" manage=off grid=2:3:1:3:1:1
fi
